### ISSUE TITLE
cannot use gs (type *"google.golang.org/grpc".Server) as type ... in argument to library.RegisterBookServiceServer

### ISSUE THREAD

**Issue by timotheecour** [johanbrandhorst/grpcweb-example#20]
after calling go get ... to fix https://github.com/johanbrandhorst/grpcweb-example/issues/19 I'm having this issue:
go run main.go
# command-line-arguments
./main.go:47:35: cannot use gs (type *"google.golang.org/grpc".Server) as type *"github.com/johanbrandhorst/grpcweb-example/vendor/google.golang.org/grpc".Server in argument to library.RegisterBookServiceServer

go version
go version go1.10.2 darwin/amd64

**Comment by johanbrandhorst** [comment]
You should not have to use `go get ./...` as it will not use the correctly vendored versions. See my comment in #19
