### ISSUE TITLE
$GOPATH/src github.com/johanbrandhorst/protobuf/proto/gopherjs.proto: File not found

### ISSUE THREAD

**Issue by joeblew99** [johanbrandhorst/grpcweb-example#9]
I am running your example code to learn more..
Had this working a few days ago, but today the make regen is failing.

I assume its looking inside the vendor folder ?
any ideas ?

````

x-MacBook-Pro:grpcweb-example apple$ make
protoc -I. -I$GOPATH/src proto/library/book_service.proto \
    	--gopherjs_out=plugins=grpc,Mgoogle/protobuf/timestamp.proto=github.com/johanbrandhorst/protobuf/ptypes/timestamp:$GOPATH/src \
    	--go_out=plugins=grpc:$GOPATH/src
github.com/johanbrandhorst/protobuf/proto/gopherjs.proto: File not found.
proto/library/book_service.proto: Import "github.com/johanbrandhorst/protobuf/proto/gopherjs.proto" was not found or had errors.
make[1]: *** [regenerate] Error 1

````

**Comment by joeblew99** [comment]
i had to git cloen it to get it working.
git clone https://github.com/johanbrandhorst/protobuf.git

This project seems to not be using the vendor folder... weird..

Still confused and would love to get to the bottom of this if you have any ideas

**Comment by johanbrandhorst** [comment]
Hi! Somehow I wasn't getting notifications for this repo do I didn't realise an issue had been raised. Terribly sorry for the delayed reply.

You're absolutely right that the proto file dependency should be vendored, that just an oversight on my part. I'll take a look at this as soon as I have time, but I would also accept PRs. Might be worthwhile adding some CI to this repo as well for future changes.
